sudo : required
services :
  -docker

before_install:
  - docker build -t shubhamhr07/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shubhamhr07/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-130165000007"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  seccret_access_key : $AWS_SECRET_KEY